name: Testing
on:
  push:
    branches:
      - '*'
jobs:
  run-unit-tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  run-e2e-tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Playwright
        run: npm install && npx playwright install --with-deps
      - name: Build and install wacat command
        run: npm run build && npm install -g
      - name: Install test-app dependencies
        run: (cd test-app/test-app && npm install)
      - name: Run tests
        run: ./run-tests.sh
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}
